# Generated by Django 5.2.1 on 2025-06-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("telegram_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=10)),
                ("age", models.PositiveIntegerField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_banned", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
